import Head from 'next/head'
import Image from 'next/image'
// import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Button from '@/components/Button'
import Navbar from '@/components/Navbar'
import Filter from '@/components/Filter'
import Filters from '@/components/Filter'

const deliveryFilters = [
  {
    id: 1,
    icon: <i className="fi fi-rr-settings-sliders absolute-center"></i>,
    title: "Filters",
  },
  {
    id: 2,
    title: "Rating: 4.0+",
  },
  {
    id: 3,
    title: "Safe and Hygienic",
  },
  {
    id: 4,
    title: "Pure Veg",
  },
  {
    id: 5,
    title: "Delivery Time",
    icon: <i className="fi fi-rr-apps-sort absolute-center"></i>,
  },
  {
    id: 6,
    title: "Great Offers",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className='max-w-7xl'>
        <Filters filterList={deliveryFilters} />
      </div>
      <div className='flex flex-col items-center justify-center min-h-screen py-2'>
      {/* <Button
        label="Click me"
        secondary
        fullWidth
        large
        onClick={() => console.log('clicked')}
        // disabled
        // outline
      /> */}
      </div>
    </>
  )
}
